<!Doctype HTML>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        <?php
        if (!isset($this->page_title)) {
            echo $this->page_title;
        } else {
            echo 'title not found';
        }
        ?>
    </title>
    <link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet/less" type="text/css" href="/css/styles.less" />
    <script src="/bower_components/less/dist/less.min.js" type="text/javascript"></script>
</head>
<?php $this->renderChild('layout/header') ?>
<?php $this->renderContent(); ?>
</body>
</html>